### ISSUE TITLE
Proposed changes to main page/TOC, Intro, left-side column

### ISSUE THREAD

**Issue by lasomethingsomething** [zalando/zmon-docs#14]
Wondering if we can merge the current page with "Intro," putting the Intro, ZMON Components, and ZMON Origins sections on the front page, inserting a link to "Getting Started" before Origins, then adding a condensed version of the TOC below the Origins paragraph.

**Comment by lasomethingsomething** [comment]
Also: In left-side column, would combine "Dashboards" and "Grafana 2 and KairosDB" sections into "Dashboards."

**Comment by lasomethingsomething** [comment]
@hjacobs @Jan-M @lmineiro ... Another suggestion: at the top of the left-side TOC, After Introduction, There is Components. 
- Under Components, I would list the four essential components and create a separate page for each one, in some kind of order that reflects how ZMON uses them. This will reduce the need for some of the other sections, make it clearer what these components do and give them an identity. You can do it like this:
- Controller: The UI and Rest API (folding in the Dashboards section)
- Worker: Checking and Alerting (folding in those sections)
- Scheduler: Testing + Anything else that fits
- event-log-service: You might want to rename this component to be more like the other three (which have nice, simple names); this one isn't too clear to me right now

The long list list of check commands primarily relate to Worker, correct?: https://zmon.readthedocs.io/en/latest/user/check-commands.html. If yes, I would put this list in/under the Worker page.

This page https://zmon.readthedocs.io/en/latest/intro.html#rest-api-and-cli combines more REST API discussion, which fits under Controller; and the CLI, which merits its own page.

**Comment by lasomethingsomething** [comment]
Another note as per chat with @Jan-M: adding install doc for the iOS and Android clients, including the GitHub-as-OAuth2 instructions. Mobile functionality distinguishes ZMON from Prometheus and is something we should definitely highlight. cc @lmineiro @hjacobs

**Comment by lasomethingsomething** [comment]
@Jan-M @hjacobs @lmineiro Saw the intro page update -- nice! What about my other suggestions? Jan voted down the suggestion about making separate pages for each essential component. Which, it seems, leaves only this one:
- This page https://zmon.readthedocs.io/en/latest/intro.html#rest-api-and-cli combines more REST API discussion, which fits under Controller; and the CLI, which merits its own page. 

Simple yes/no is enough :)

**Comment by hjacobs** [comment]
@LappleApple we should not arrange the docs ("User's Guide") according to the components as the components are not what users would really care about (only admins).

**Comment by lasomethingsomething** [comment]
@hjacobs Right, the only question hanging from before is in my comment immediately above your last one. And also this one:

In left-side column, would combine "Dashboards" and "Grafana 2 and KairosDB" sections into "Dashboards."

**Comment by Jan-M** [comment]
@LappleApple imho not.

Grafana is basically Grafana with all its KairosDB related features, whereas the Dashboard section should realy cover what we call the ZMON dashboard, which can include widgets, chats, and alerts filtered by tags/teams.

**Comment by lasomethingsomething** [comment]
@Jan-M Think about which presentation will benefit the user. Ultimately they don't care as much about "how ZMON works" as much as they do about "how to use ZMON."
